export const GET_USER_JWT = 'GET_USER_JWT';
export const SET_USER_JWT = 'SET_USER_JWT';

export const GET_POSTS_PAGINATION = 'GET_POSTS_PAGINATION';
export const SET_POSTS_PAGINATION = 'SET_POSTS_PAGINATION';

export const GET_USERS_PAGINATION = 'GET_USERS_PAGINATION';
export const SET_USERS_PAGINATION = 'SET_USERS_PAGINATION';